name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run golint
        run: golint ./...

      - name: Run gocyclo
        run: gocyclo .
